export default {
  ADD_CONTACT: 'ADD_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  UPDATE_CONTACT: 'UDPATE_CONTACT',
  SEARCH_CONTACT: 'SEARCH_CONTACT',
  INITIALIZE_CONTACTS: 'INITIALIZE_CONTACTS'
};
